# basket of securities with strong 9SMA support
SMA9_securities = [
    # ['FNV', 'NYSE'],
    # ['GDX', 'ARCA'],
    # ['GOLD', 'NYSE'],
    ['TLT', 'NASDAQ'],
    ['FUTU', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['TAL', 'NYSE'],
    ['ZTO', 'NYSE'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
]

# basket of securities with strong 20SMA support
SMA20_securities = [
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    # ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    # ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    # ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['CRON', 'NASDAQ'],
    ['BGNE', 'NASDAQ'],
    ['EBAY', 'NASDAQ'],
    ['ZLAB', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['TDOC', 'NYSE'],
    ['XRT', 'ARCA'],
    ['PLUG', 'NASDAQ'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],

]

# basket of securities with strong 50SMA support
SMA50_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA  SHORT CANDIDATE
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['SLV', 'ARCA'],
    ['EEM', 'ARCA'],
    ['SOL', 'NYSE'],
    ['NTES', 'NASDAQ'],
    ['MARA', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['ROKU', 'NASDAQ'],
    ['NIU', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['AAPL', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['MCHI', 'NASDAQ'],
    ['DQ', 'NYSE'],
    ['BILI', 'NASDAQ'],
    ['KWEB', 'ARCA'],
    ['VNET', 'NASDAQ'],
    ['MAXR', 'NYSE'],
    ['FXI', 'ARCA'],
    ['MELI', 'NASDAQ'],
    ['ICLN', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['BBY', 'NYSE'],
    ['APPS', 'NASDAQ'],
    ['LRCX', 'NASDAQ'],
    ['IBB', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['TAN', 'ARCA'],
    ['BHP', 'NYSE'],
    ['MU', 'NASDAQ'],
    ['BIDU', 'NASDAQ'],
    ['CSIQ', 'NASDAQ'],
    ['DE', 'NYSE'],
    ['GDS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['UUUU', 'AMEX'],
    ['KLAC', 'NASDAQ'],
    ['JPM', 'NYSE'],
    ['MLM', 'NYSE'],
    ['ESTC', 'NYSE'],
    ['ZS', 'NASDAQ'],
    ['NXE', 'AMEX'],
    ['FVRR', 'NYSE'],
    ['RIOT', 'NASDAQ'],
    ['IWM', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['PTON', 'NASDAQ'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['LAZR', 'NASDAQ'],
    # ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA']
]

# basket of securities with strong 200SMA support
SMA200_securities = [
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['CCJ', 'NYSE'],
    ['PINS', 'NYSE'],
    ['HD', 'NYSE'],
    ['INTU', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['PG', 'NYSE'],    #SHORT CANDIDATE
    ['ANTM', 'NYSE'],
    ['BABA', 'NYSE'],
    ['SQ', 'NYSE'],
    ['SBUX', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['SHOP', 'NYSE'],
    ['JO', 'ARCA'],
    ['DDOG', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['CHDN', 'NASDAQ'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['NET', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['EDU', 'NYSE'],
    ['SPY', 'ARCA'],
    ['ATVI', 'NASDAQ'],
    ['UNP', 'NYSE'],
    ['TEAM', 'NASDAQ'],
    ['IWB', 'ARCA'],
    ['DOYU', 'NASDAQ'],
    ['PYPL', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['DIA', 'ARCA'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

# all securities, bollinger bands currently set to 2.5 standard deviations
lowerBB_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['ESTC', 'NYSE'],
    ['FNV', 'NYSE'],
    ['GDX', 'ARCA'],
    ['GOLD', 'NYSE'],
    ['IWM', 'ARCA'],
    ['TLT', 'NASDAQ'],
    ['BABA', 'NYSE'],
    ['BGNE', 'NASDAQ'],
    ['BILI', 'NASDAQ'],
    ['DQ', 'NYSE'],
    ['FUTU', 'NASDAQ'],
    ['FXI', 'ARCA'],
    ['GDS', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['KWEB', 'ARCA'],
    ['MCHI', 'NASDAQ'],
    ['NIU', 'NASDAQ'],
    ['NTES', 'NASDAQ'],
    ['SOL', 'NYSE'],
    ['TAL', 'NYSE'],
    ['ZLAB', 'NASDAQ'],
    ['ZTO', 'NYSE'],
    ['LRCX', 'NASDAQ'],
    ['KLAC', 'NASDAQ'],
    ['TDOC', 'NYSE'],
    ['BIDU', 'NASDAQ'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
    ['IBB', 'NASDAQ'],
    ['ATVI', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['CRON', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['BHP', 'NYSE'],
    ['DIA', 'ARCA'],
    ['EBAY', 'NASDAQ'],
    ['MU', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['MARA', 'NASDAQ'],
    ['EEM', 'ARCA'],
    ['FVRR', 'NYSE'],
    ['VNET', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['ROKU', 'NASDAQ'],
    ['SPY', 'ARCA'],
    ['XRT', 'ARCA'],
    ['ZS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['PLUG', 'NASDAQ'],
    ['MLM', 'NYSE'],
    ['TAN', 'ARCA'],
    ['PYPL', 'NASDAQ'],
    ['APPS', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['MELI', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['ICLN', 'NASDAQ'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['IWB', 'ARCA'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],
    ['MAXR', 'NYSE'],
    ['DE', 'NYSE'],
    ['SLV', 'ARCA'],
    ['AAPL', 'NASDAQ'],
    ['BBY', 'NYSE'],
    ['CSIQ', 'NASDAQ'],
    ['DDOG', 'NASDAQ'],
    ['UUUU', 'AMEX'],
    ['JPM', 'NYSE'],
    ['CCJ', 'NYSE'],
    ['NXE', 'AMEX'],
    ['RIOT', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['JO', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['HD', 'NYSE'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['NET', 'NYSE'],
    ['PINS', 'NYSE'],
    ['PTON', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SBUX', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['SQ', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['TEAM', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['INTU', 'NASDAQ'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CHDN', 'NASDAQ'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['SHOP', 'NYSE'],
    ['LAZR', 'NASDAQ'],
    ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA'],
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['PG', 'NYSE'],
    ['ANTM', 'NYSE'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['EDU', 'NYSE'],
    ['UNP', 'NYSE'],
    ['DOYU', 'NASDAQ'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

# all securities, bollinger bands currently set to 2.5 standard deviations
upperBB_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['ESTC', 'NYSE'],
    ['FNV', 'NYSE'],
    ['GDX', 'ARCA'],
    ['GOLD', 'NYSE'],
    ['IWM', 'ARCA'],
    ['TLT', 'NASDAQ'],
    ['BABA', 'NYSE'],
    ['BGNE', 'NASDAQ'],
    ['BILI', 'NASDAQ'],
    ['DQ', 'NYSE'],
    ['FUTU', 'NASDAQ'],
    ['FXI', 'ARCA'],
    ['GDS', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['KWEB', 'ARCA'],
    ['MCHI', 'NASDAQ'],
    ['NIU', 'NASDAQ'],
    ['NTES', 'NASDAQ'],
    ['SOL', 'NYSE'],
    ['TAL', 'NYSE'],
    ['ZLAB', 'NASDAQ'],
    ['ZTO', 'NYSE'],
    ['LRCX', 'NASDAQ'],
    ['KLAC', 'NASDAQ'],
    ['TDOC', 'NYSE'],
    ['BIDU', 'NASDAQ'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
    ['IBB', 'NASDAQ'],
    ['ATVI', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['CRON', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['BHP', 'NYSE'],
    ['DIA', 'ARCA'],
    ['EBAY', 'NASDAQ'],
    ['MU', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['MARA', 'NASDAQ'],
    ['EEM', 'ARCA'],
    ['FVRR', 'NYSE'],
    ['VNET', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['ROKU', 'NASDAQ'],
    ['SPY', 'ARCA'],
    ['XRT', 'ARCA'],
    ['ZS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['PLUG', 'NASDAQ'],
    ['MLM', 'NYSE'],
    ['TAN', 'ARCA'],
    ['PYPL', 'NASDAQ'],
    ['APPS', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['MELI', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['ICLN', 'NASDAQ'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['IWB', 'ARCA'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],
    ['MAXR', 'NYSE'],
    ['DE', 'NYSE'],
    ['SLV', 'ARCA'],
    ['AAPL', 'NASDAQ'],
    ['BBY', 'NYSE'],
    ['CSIQ', 'NASDAQ'],
    ['DDOG', 'NASDAQ'],
    ['UUUU', 'AMEX'],
    ['JPM', 'NYSE'],
    ['CCJ', 'NYSE'],
    ['NXE', 'AMEX'],
    ['RIOT', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['JO', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['HD', 'NYSE'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['NET', 'NYSE'],
    ['PINS', 'NYSE'],
    ['PTON', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SBUX', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['SQ', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['TEAM', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['INTU', 'NASDAQ'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CHDN', 'NASDAQ'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['SHOP', 'NYSE'],
    ['LAZR', 'NASDAQ'],
    ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA'],
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['PG', 'NYSE'],
    ['ANTM', 'NYSE'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['EDU', 'NYSE'],
    ['UNP', 'NYSE'],
    ['DOYU', 'NASDAQ'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

# may be using this list to further refactor code sometime in the future
buckets = [
    [SMA9_securities, 'sma9'],
    [SMA20_securities, 'sma20'],
    [SMA50_securities, 'sma50'],
    [SMA200_securities, 'sma200'],
    [lowerBB_securities, 'lowerbb'],
    [upperBB_securities, 'upperbb']
]

# full list of securities with Industry, Category, Subcategory
industry_category_subcategory = [
    ["APHA", "NASDAQ", "Consumer, Non-cyclical", "Pharmaceuticals", "Medical-Drugs"],
    ["XPER", "NASDAQ", "Technology", "Software", "Computer Software"],
    ["ACB", "NYSE", "Consumer, Non-cyclical", "Pharmaceuticals", "Medical-Drugs"],
    ["GRWG", "NASDAQ", "Consumer, Cyclical", "Retail", "Retail-Gardening Prod"],
    ["USO", "ARCA", "", "", ""],
    ["OIH", "ARCA", "", "", ""],
    ["SMH", "NASDAQ", "", "", ""],
    ["SRAC", "NASDAQ", "Diversified", "Holding Companies-Divers", "Specified Purpose Acquis"],
    ["ONEM", "NASDAQ", "Technology", "Software", "Medical Information Sys"],
    ["DADA", "NASDAQ", "Communications", "Internet", "Internet Content-Info/Ne"],
    ["MGNI", "NASDAQ", "Communications", "Internet", "E-Marketing/Info"],
    ["LMND", "NYSE", "Financial", "Insurance", "Property/Casualty Ins"],
    ["LI", "NASDAQ", "Consumer, Cyclical", "Auto Manufacturers", "Auto-Cars/Light Trucks"],
    ["XPEV", "NYSE", "Consumer, Cyclical", "Auto Manufacturers", "Auto-Cars/Light Trucks"],
    ["MSOS", "ARCA", "", "", ""],
    ["CRSR", "NASDAQ", "Technology", "Computers", "Computers-Other"],
    ["CTEC", "NASDAQ", "", "", ""],
    ["ESTC", "NYSE", "Technology", "Software", "Applications Software"],
    ["FNV", "NYSE", "Basic Materials", "Mining", "Gold Mining"],
    ["GDX", "ARCA", "", "", ""],
    ["GOLD", "NYSE", "Basic Materials", "Mining", "Gold Mining"],
    ["IWM", "ARCA", "", "", ""],
    ["TLT", "NASDAQ", "", "", ""],
    ["BABA", "NYSE", "Communications", "Internet", "E-Commerce/Products"],
    ["BGNE", "NASDAQ", "Consumer, Non-cyclical", "Biotechnology", "Medical-Biomedical/Gene"],
    ["BILI", "NASDAQ", "Technology", "Software", "Entertainment Software"],
    ["DQ", "NYSE", "Basic Materials", "Chemicals", "Chemicals-Specialty"],
    ["FUTU", "NASDAQ", "Financial", "Diversified Finan Serv", "Finance-Invest Bnkr/Brkr"],
    ["FXI", "ARCA", "", "", ""],
    ["GDS", "NASDAQ", "Communications", "Telecommunications", "Telecom Services"],
    ["IQ", "NASDAQ", "Communications", "Internet", "Internet Content-Info/Ne"],
    ["JMIA", "NYSE", "Communications", "Internet", "E-Marketing/Info"],
    ["KWEB", "ARCA", "", "", ""],
    ["MCHI", "NASDAQ", "", "", ""],
    ["NIU", "NASDAQ", "Consumer, Cyclical", "Leisure Time", "Motorcycle/Motor Scooter"],
    ["NTES", "NASDAQ", "Technology", "Software", "Entertainment Software"],
    ["SOL", "NYSE", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["TAL", "NYSE", "Consumer, Non-cyclical", "Commercial Services", "Schools"],
    ["ZLAB", "NASDAQ", "Consumer, Non-cyclical", "Biotechnology", "Medical-Biomedical/Gene"],
    ["ZTO", "NYSE", "Industrial", "Transportation", "Transport-Services"],
    ["LRCX", "NASDAQ", "Technology", "Semiconductors", "Semiconductor Equipment"],
    ["KLAC", "NASDAQ", "Technology", "Semiconductors", "Semiconductor Equipment"],
    ["TDOC", "NYSE", "Consumer, Non-cyclical", "Healthcare-Services", "Medical Labs and Testing Srv"],
    ["BIDU", "NASDAQ", "Communications", "Internet", "Web Portals/ISP"],
    ["UUP", "ARCA", "", "", ""],
    ["SPCE", "NYSE", "Consumer, Cyclical", "Leisure Time", "Travel Services"],
    ["IRDM", "NASDAQ", "Communications", "Telecommunications", "Satellite Telecom"],
    ["DDD", "NYSE", "Technology", "Computers", "Computers-Other"],
    ["IBB", "NASDAQ", "", "", ""],
    ["ATVI", "NASDAQ", "Technology", "Software", "Entertainment Software"],
    ["VFF", "NASDAQ", "Consumer, Non-cyclical", "Agriculture", "Agricultural Operations"],
    ["CRON", "NASDAQ", "Consumer, Non-cyclical", "Household Products/Wares", "Consumer Products-Misc"],
    ["RIO", "NYSE", "Basic Materials", "Mining", "Metal-Diversified"],
    ["BHP", "NYSE", "Basic Materials", "Mining", "Diversified Minerals"],
    ["DIA", "ARCA", "", "", ""],
    ["EBAY", "NASDAQ", "Communications", "Internet", "E-Commerce/Products"],
    ["MU", "NASDAQ", "Technology", "Semiconductors", "Electronic Compo-Semicon"],
    ["CHWY", "NYSE", "Communications", "Internet", "E-Commerce/Products"],
    ["MARA", "NASDAQ", "Diversified", "Holding Companies-Divers", "Diversified Operations"],
    ["EEM", "ARCA", "", "", ""],
    ["FVRR", "NYSE", "Communications", "Internet", "E-Commerce/Services"],
    ["VNET", "NASDAQ", "Communications", "Internet", "Internet Connectiv Svcs"],
    ["FCEL", "NASDAQ", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["ROKU", "NASDAQ", "Communications", "Internet", "Internet Content-Entmnt"],
    ["SPY", "ARCA", "", "", ""],
    ["XRT", "ARCA", "", "", ""],
    ["ZS", "NASDAQ", "Technology", "Computers", "Computer Data Security"],
    ["VIPS", "NYSE", "Communications", "Internet", "E-Commerce/Products"],
    ["PLUG", "NASDAQ", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["MLM", "NYSE", "Industrial", "Building Materials", "Bldg Prod-Cement/Aggreg"],
    ["TAN", "ARCA", "", "", ""],
    ["PYPL", "NASDAQ", "Consumer, Non-cyclical", "Commercial Services", "Commercial Serv-Finance"],
    ["APPS", "NASDAQ", "Technology", "Software", "Software Tools"],
    ["PENN", "NASDAQ", "Consumer, Cyclical", "Entertainment", "Racetracks"],
    ["MELI", "NASDAQ", "Communications", "Internet", "E-Commerce/Services"],
    ["ENPH", "NASDAQ", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["PBW", "ARCA", "", "", ""],
    ["ICLN", "NASDAQ", "", "", ""],
    ["SPWR", "NASDAQ", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["CYBR", "NASDAQ", "Technology", "Computers", "Computer Data Security"],
    ["NXPI", "NASDAQ", "Technology", "Semiconductors", "Semicon Compo-Intg Circu"],
    ["ARKK", "ARCA", "", "", ""],
    ["IWB", "ARCA", "", "", ""],
    ["YOLO", "ARCA", "", "", ""],
    ["THCX", "ARCA", "", "", ""],
    ["MJ", "ARCA", "", "", ""],
    ["TLRY", "NASDAQ", "Consumer, Non-cyclical", "Pharmaceuticals", "Medical-Drugs"],
    ["MAXR", "NYSE", "Communications", "Telecommunications", "Wireless Equipment"],
    ["DE", "NYSE", "Industrial", "Machinery-Diversified", "Machinery-Farm"],
    ["SLV", "ARCA", "", "", ""],
    ["AAPL", "NASDAQ", "Technology", "Computers", "Computers"],
    ["BBY", "NYSE", "Consumer, Cyclical", "Retail", "Retail-Consumer Electron"],
    ["CSIQ", "NASDAQ", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["DDOG", "NASDAQ", "Technology", "Software", "Computer Software"],
    ["UUUU", "AMEX", "Basic Materials", "Mining", "Non-Ferrous Metals"],
    ["JPM", "NYSE", "Financial", "Banks", "Diversified Banking Inst"],
    ["CCJ", "NYSE", "Basic Materials", "Mining", "Non-Ferrous Metals"],
    ["NXE", "AMEX", "Basic Materials", "Mining", "Non-Ferrous Metals"],
    ["RIOT", "NASDAQ", "Consumer, Non-cyclical", "Commercial Services", "Commercial Serv-Finance"],
    ["DECK", "NYSE", "Consumer, Cyclical", "Apparel", "Apparel Manufacturers"],
    ["DOCU", "NASDAQ", "Technology", "Software", "Data Processing/Mgmt"],
    ["JO", "ARCA", "", "", ""],
    ["FSLR", "NASDAQ", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["XLF", "ARCA", "", "", ""],
    ["ETSY", "NASDAQ", "Communications", "Internet", "E-Commerce/Products"],
    ["GPS", "NYSE", "Consumer, Cyclical", "Retail", "Retail-Apparel/Shoe"],
    ["HD", "NYSE", "Consumer, Cyclical", "Retail", "Retail-Building Products"],
    ["LOW", "NYSE", "Consumer, Cyclical", "Retail", "Retail-Building Products"],
    ["CRWD", "NASDAQ", "Technology", "Computers", "Computer Data Security"],
    ["NET", "NYSE", "Technology", "Software", "Computer Software"],
    ["PINS", "NYSE", "Communications", "Internet", "Internet Content-Entmnt"],
    ["PTON", "NASDAQ", "Consumer, Cyclical", "Leisure Time", "Athletic Equipment"],
    ["XLE", "ARCA", "", "", ""],
    ["TSLA", "NASDAQ", "Consumer, Cyclical", "Auto Manufacturers", "Auto-Cars/Light Trucks"],
    ["QCOM", "NASDAQ", "Technology", "Semiconductors", "Semicon Compo-Intg Circu"],
    ["QQQ", "NYSE", "", "", ""],
    ["CAT", "NYSE", "Industrial", "Machinery-Constr and Mining", "Machinery-Constr and Mining"],
    ["RUN", "NASDAQ", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["BLNK", "NASDAQ", "Industrial", "Machinery-Constr and Mining", "Machinery-Electric Util"],
    ["SBUX", "NASDAQ", "Consumer, Cyclical", "Retail", "Retail-Restaurants"],
    ["SNAP", "NYSE", "Communications", "Internet", "Internet Content-Entmnt"],
    ["SQ", "NYSE", "Consumer, Non-cyclical", "Commercial Services", "Commercial Serv-Finance"],
    ["TGT", "NYSE", "Consumer, Cyclical", "Retail", "Retail-Discount"],
    ["TWLO", "NYSE", "Technology", "Software", "Computer Software"],
    ["XHB", "ARCA", "", "", ""],
    ["Z", "NASDAQ", "Communications", "Internet", "E-Commerce/Services"],
    ["JD", "NASDAQ", "Communications", "Internet", "E-Commerce/Products"],
    ["NIO", "NYSE", "Consumer, Cyclical", "Auto Manufacturers", "Auto-Cars/Light Trucks"],
    ["PDD", "NASDAQ", "Communications", "Internet", "E-Commerce/Products"],
    ["IGV", "BATS", "", "", ""],
    ["TEAM", "NASDAQ", "Technology", "Software", "Enterprise Software/Serv"],
    ["SEDG", "NASDAQ", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["INTU", "NASDAQ", "Technology", "Software", "Applications Software"],
    ["GOOGL", "NASDAQ", "Communications", "Internet", "Web Portals/ISP"],
    ["NVAX", "NASDAQ", "Consumer, Non-cyclical", "Biotechnology", "Medical-Biomedical/Gene"],
    ["OKTA", "NASDAQ", "Communications", "Internet", "Internet Applic Sftwr"],
    ["SE", "NYSE", "Technology", "Software", "Entertainment Software"],
    ["CHDN", "NASDAQ", "Consumer, Cyclical", "Entertainment", "Racetracks"],
    ["CGC", "NASDAQ", "Consumer, Non-cyclical", "Pharmaceuticals", "Medical-Drugs"],
    ["IIPR", "NYSE", "Financial", "REITS", "REITS-Warehouse/Industr"],
    ["FTCH", "NYSE", "Communications", "Internet", "E-Commerce/Products"],
    ["ZI", "NASDAQ", "Technology", "Software", "Computer Software"],
    ["SHOP", "NYSE", "Communications", "Internet", "Internet Applic Sftwr"],
    ["LAZR", "NASDAQ", "Consumer, Cyclical", "Auto Parts and Equipment", "Auto/Trk Prts and Equip-Orig"],
    ["NEM", "NYSE", "Basic Materials", "Mining", "Gold Mining"],
    ["MDB", "NASDAQ", "Technology", "Software", "Computer Software"],
    ["FTNT", "NASDAQ", "Technology", "Computers", "Computer Data Security"],
    ["BZH", "NYSE", "Consumer, Cyclical", "Home Builders", "Bldg-Residential/Commer"],
    ["XLK", "ARCA", "", "", ""],
    ["GLD", "ARCA", "", "", ""],
    ["ADBE", "NASDAQ", "Technology", "Software", "Electronic Forms"],
    ["COST", "ARCA", "Consumer, Cyclical", "Retail", "Retail-Discount"],
    ["FSLY", "NYSE", "Technology", "Software", "Computer Software"],
    ["MSFT", "NASDAQ", "Technology", "Software", "Applications Software"],
    ["NFLX", "NASDAQ", "Communications", "Internet", "Internet Content-Entmnt"],
    ["NVDA", "NASDAQ", "Technology", "Semiconductors", "Electronic Compo-Semicon"],
    ["PG", "NYSE", "Consumer, Non-cyclical", "Cosmetics/Personal Care", "Cosmetics and Toiletries"],
    ["ANTM", "NYSE", "Consumer, Non-cyclical", "Healthcare-Services", "Medical-HMO"],
    ["TTD", "NASDAQ", "Communications", "Advertising", "Advertising Services"],
    ["TWTR", "NYSE", "Communications", "Internet", "Internet Content-Entmnt"],
    ["UPS", "NYSE", "Industrial", "Transportation", "Transport-Services"],
    ["WMT", "NYSE", "Consumer, Cyclical", "Retail", "Retail-Discount"],
    ["EDU", "NYSE", "Consumer, Non-cyclical", "Commercial Services", "Schools"],
    ["UNP", "NYSE", "Industrial", "Transportation", "Transport-Rail"],
    ["DOYU", "NASDAQ", "Technology", "Software", "Entertainment Software"],
    ["JKS", "NYSE", "Energy", "Energy-Alternate Sources", "Energy-Alternate Sources"],
    ["HTHT", "NASDAQ", "Consumer, Cyclical", "Lodging", "Hotels and Motels"],
    ["NFLX", "NASDAQ", "Communications", "Internet", "Internet Content-Entmnt"],
    ["FB", "NASDAQ", "Communications", "Internet", "Internet Content-Entmnt"],
    ["CRM", "NYSE", "Technology", "Software", "Enterprise Software/Serv"],
    ["AMZN", "NASDAQ", "Communications", "Internet", "E-Commerce/Products"],
    ["ZM", "NASDAQ", "Technology", "Software", "Communications Software"],
    ["MRNA", "NASDAQ", "Consumer, Non-cyclical", "Biotechnology", "Medical-Biomedical/Gene"],
    ["AMD", "NASDAQ", "Technology", "Semiconductors", "Electronic Compo-Semicon"],
]
