SMA9_securities = [
    # ['FNV', 'NYSE'],
    # ['GDX', 'ARCA'],
    # ['GOLD', 'NYSE'],
    ['TLT', 'NASDAQ'],
    ['BABA', 'NYSE'],
    ['DQ', 'NYSE'],
    ['FUTU', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['KWEB', 'ARCA'],
    ['NIU', 'NASDAQ'],
    ['NTES', 'NASDAQ'],
    ['TAL', 'NYSE'],
    ['ZTO', 'NYSE'],
    ['TDOC', 'NYSE'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
]

SMA20_securities = [
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['CRON', 'NASDAQ'],
    ['BGNE', 'NASDAQ'],
    ['SOL', 'NYSE'],
    ['BILI', 'NASDAQ'],
    ['EBAY', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['EEM', 'ARCA'],
    ['ZLAB', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['ROKU', 'NASDAQ'],
    ['XRT', 'ARCA'],
    ['PLUG', 'NASDAQ'],
    ['APPS', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],
    ['MAXR', 'NYSE'],
]

SMA50_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['SLV', 'ARCA'],
    ['MARA', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['AAPL', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['MCHI', 'NASDAQ'],
    ['VNET', 'NASDAQ'],
    ['FXI', 'ARCA'],
    ['MELI', 'NASDAQ'],
    ['ICLN', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['BBY', 'NYSE'],
    ['LRCX', 'NASDAQ'],
    ['IBB', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['TAN', 'ARCA'],
    ['BHP', 'NYSE'],
    ['MU', 'NASDAQ'],
    ['BIDU', 'NASDAQ'],
    ['CSIQ', 'NASDAQ'],
    ['DE', 'NYSE'],
    ['GDS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['UUUU', 'AMEX'],
    ['KLAC', 'NASDAQ'],
    ['JPM', 'NYSE'],
    ['MLM', 'NYSE'],
    ['ESTC', 'NYSE'],
    ['CCJ', 'NYSE'],
    ['ZS', 'NASDAQ'],
    ['NXE', 'AMEX'],
    ['FVRR', 'NYSE'],
    ['RIOT', 'NASDAQ'],
    ['IWM', 'ARCA'],
    ['JO', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['HD', 'NYSE'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['PTON', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['LAZR', 'NASDAQ'],
    # ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA']
]

SMA200_securities = [
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['PINS', 'NYSE'],
    ['INTU', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['PG', 'NYSE'],
    ['ANTM', 'NYSE'],
    ['SQ', 'NYSE'],
    ['SBUX', 'NASDAQ'],
    ['SHOP', 'NYSE'],
    ['DDOG', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['CHDN', 'NASDAQ'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['NET', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['EDU', 'NYSE'],
    ['SPY', 'ARCA'],
    ['ATVI', 'NASDAQ'],
    ['UNP', 'NYSE'],
    ['TEAM', 'NASDAQ'],
    ['IWB', 'ARCA'],
    ['DOYU', 'NASDAQ'],
    ['PYPL', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['DIA', 'ARCA'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

lowerBB_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['ESTC', 'NYSE'],
    ['FNV', 'NYSE'],
    ['GDX', 'ARCA'],
    ['GOLD', 'NYSE'],
    ['IWM', 'ARCA'],
    ['TLT', 'NASDAQ'],
    ['BABA', 'NYSE'],
    ['BGNE', 'NASDAQ'],
    ['BILI', 'NASDAQ'],
    ['DQ', 'NYSE'],
    ['FUTU', 'NASDAQ'],
    ['FXI', 'ARCA'],
    ['GDS', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['KWEB', 'ARCA'],
    ['MCHI', 'NASDAQ'],
    ['NIU', 'NASDAQ'],
    ['NTES', 'NASDAQ'],
    ['SOL', 'NYSE'],
    ['TAL', 'NYSE'],
    ['ZLAB', 'NASDAQ'],
    ['ZTO', 'NYSE'],
    ['LRCX', 'NASDAQ'],
    ['KLAC', 'NASDAQ'],
    ['TDOC', 'NYSE'],
    ['BIDU', 'NASDAQ'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
    ['IBB', 'NASDAQ'],
    ['ATVI', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['CRON', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['BHP', 'NYSE'],
    ['DIA', 'ARCA'],
    ['EBAY', 'NASDAQ'],
    ['MU', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['MARA', 'NASDAQ'],
    ['EEM', 'ARCA'],
    ['FVRR', 'NYSE'],
    ['VNET', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['ROKU', 'NASDAQ'],
    ['SPY', 'ARCA'],
    ['XRT', 'ARCA'],
    ['ZS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['PLUG', 'NASDAQ'],
    ['MLM', 'NYSE'],
    ['TAN', 'ARCA'],
    ['PYPL', 'NASDAQ'],
    ['APPS', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['MELI', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['ICLN', 'NASDAQ'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['IWB', 'ARCA'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],
    ['MAXR', 'NYSE'],
    ['DE', 'NYSE'],
    ['SLV', 'ARCA'],
    ['AAPL', 'NASDAQ'],
    ['BBY', 'NYSE'],
    ['CSIQ', 'NASDAQ'],
    ['DDOG', 'NASDAQ'],
    ['UUUU', 'AMEX'],
    ['JPM', 'NYSE'],
    ['CCJ', 'NYSE'],
    ['NXE', 'AMEX'],
    ['RIOT', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['JO', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['HD', 'NYSE'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['NET', 'NYSE'],
    ['PINS', 'NYSE'],
    ['PTON', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SBUX', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['SQ', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['TEAM', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['INTU', 'NASDAQ'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CHDN', 'NASDAQ'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['SHOP', 'NYSE'],
    ['LAZR', 'NASDAQ'],
    ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA'],
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['PG', 'NYSE'],
    ['ANTM', 'NYSE'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['EDU', 'NYSE'],
    ['UNP', 'NYSE'],
    ['DOYU', 'NASDAQ'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

upperBB_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['ESTC', 'NYSE'],
    ['FNV', 'NYSE'],
    ['GDX', 'ARCA'],
    ['GOLD', 'NYSE'],
    ['IWM', 'ARCA'],
    ['TLT', 'NASDAQ'],
    ['BABA', 'NYSE'],
    ['BGNE', 'NASDAQ'],
    ['BILI', 'NASDAQ'],
    ['DQ', 'NYSE'],
    ['FUTU', 'NASDAQ'],
    ['FXI', 'ARCA'],
    ['GDS', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['KWEB', 'ARCA'],
    ['MCHI', 'NASDAQ'],
    ['NIU', 'NASDAQ'],
    ['NTES', 'NASDAQ'],
    ['SOL', 'NYSE'],
    ['TAL', 'NYSE'],
    ['ZLAB', 'NASDAQ'],
    ['ZTO', 'NYSE'],
    ['LRCX', 'NASDAQ'],
    ['KLAC', 'NASDAQ'],
    ['TDOC', 'NYSE'],
    ['BIDU', 'NASDAQ'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
    ['IBB', 'NASDAQ'],
    ['ATVI', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['CRON', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['BHP', 'NYSE'],
    ['DIA', 'ARCA'],
    ['EBAY', 'NASDAQ'],
    ['MU', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['MARA', 'NASDAQ'],
    ['EEM', 'ARCA'],
    ['FVRR', 'NYSE'],
    ['VNET', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['ROKU', 'NASDAQ'],
    ['SPY', 'ARCA'],
    ['XRT', 'ARCA'],
    ['ZS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['PLUG', 'NASDAQ'],
    ['MLM', 'NYSE'],
    ['TAN', 'ARCA'],
    ['PYPL', 'NASDAQ'],
    ['APPS', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['MELI', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['ICLN', 'NASDAQ'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['IWB', 'ARCA'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],
    ['MAXR', 'NYSE'],
    ['DE', 'NYSE'],
    ['SLV', 'ARCA'],
    ['AAPL', 'NASDAQ'],
    ['BBY', 'NYSE'],
    ['CSIQ', 'NASDAQ'],
    ['DDOG', 'NASDAQ'],
    ['UUUU', 'AMEX'],
    ['JPM', 'NYSE'],
    ['CCJ', 'NYSE'],
    ['NXE', 'AMEX'],
    ['RIOT', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['JO', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['HD', 'NYSE'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['NET', 'NYSE'],
    ['PINS', 'NYSE'],
    ['PTON', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SBUX', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['SQ', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['TEAM', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['INTU', 'NASDAQ'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CHDN', 'NASDAQ'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['SHOP', 'NYSE'],
    ['LAZR', 'NASDAQ'],
    ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA'],
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['PG', 'NYSE'],
    ['ANTM', 'NYSE'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['EDU', 'NYSE'],
    ['UNP', 'NYSE'],
    ['DOYU', 'NASDAQ'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

buckets = [
    [SMA9_securities, 'sma9'],
    [SMA20_securities, 'sma20'],
    [SMA50_securities, 'sma50'],
    [SMA200_securities, 'sma200'],
    [lowerBB_securities, 'lowerbb'],
    [upperBB_securities, 'upperbb']
]
