# basket of securities with strong 9SMA support
SMA9_securities = [
    ["FNV", "NYSE", "goldmining", "goldmining"],
    ["GDX", "ARCA", "goldmining", "goldmining"],
    ["gold", "NYSE", "goldmining", "goldmining"],
    ["TLT", "NASDAQ", "etf", "treasuries"],
    ["FUTU", "NASDAQ", "financial", "china"],
    ["IQ", "NASDAQ", "communications", "china"],
    ["JMIA", "NYSE", "communications", "china"],
    ["TAL", "NYSE", "consumerNonCyclical", "china"],
    ["ZTO", "NYSE", "industrial", "china"],
    ["UUP", "ARCA", "etf", "treasuries"],
    ["SPCE", "NYSE", "technology", "auto"],
    ["IRDM", "NASDAQ", "communications", "telecommunications"],
    ["DDD", "NYSE", "technology", "computers"],
]


# basket of securities with strong 20SMA support
SMA20_securities = [
    ["USO", "ARCA", "etf", "energy"],
    ["ONEM", "NASDAQ", "technology", "software"],
    ["DADA", "NASDAQ", "communications", "internet"],
    ["MGNI", "NASDAQ", "communications", "internet"],
    ["LI", "NASDAQ", "consumerCyclical", "auto"],
    ["XPEV", "NYSE", "consumerCyclical", "auto"],
    ["MSOS", "ARCA", "etf", "cannabis"],
    ["CRSR", "NASDAQ", "technology", "computers"],
    ["CTEC", "NASDAQ", "etf", "alternateEnergy"],
    ["CRON", "NASDAQ", "cannabis", "cannabis"],
    ["BGNE", "NASDAQ", "consumerNonCyclical", "china"],
    ["EBAY", "NASDAQ", "communications", "internet"],
    ["ZLAB", "NASDAQ", "consumerNonCyclical", "china"],
    ["FCEL", "NASDAQ", "energy", "alternateEnergy"],
    ["TDOC", "NYSE", "technology", "software"],
    ["XRT", "ARCA", "etf", "retail"],
    ["PLUG", "NASDAQ", "energy", "alternateEnergy"],
    ["SPWR", "NASDAQ", "energy", "alternateEnergy"],
    ["CYBR", "NASDAQ", "technology", "cybersecurity"],
    ["YOLO", "ARCA", "etf", "cannabis"],
    ["THCX", "ARCA", "etf", "cannabis"],
    ["MJ", "ARCA", "etf", "cannabis"],
    ["TLRY", "NASDAQ", "cannabis", "cannabis"],
]

# basket of securities with strong 50SMA support
SMA50_securities = [
    ["APHA", "NASDAQ", "cannabis", "cannabis"],
    ["XPER", "NASDAQ", "technology", "software"],
    ["ACB", "NYSE", "cannabis", "cannabis"],
    ["GRWG", "NASDAQ", "cannabis", "cannabis"],
    ["OIH", "ARCA", "etf", "energy"],
    ["SMH", "NASDAQ", "etf", "semiconductors"],
    ["SRAC", "NASDAQ", "cannabis", "cannabis"],
    ["LMND", "NYSE", "financial", "financial"],
    ["SLV", "ARCA", "preciousMetals", "silver"],
    ["EEM", "ARCA", "etf", "china"],
    ["SOL", "NYSE", "energy", "china"],
    ["NTES", "NASDAQ", "technology", "china"],
    ["MARA", "NASDAQ", "blockchain", "blockchain"],
    ["PBW", "ARCA", "etf", "alternateEnergy"],
    ["ROKU", "NASDAQ", "communications", "internet"],
    ["NIU", "NASDAQ", "consumerCyclical", "china"],
    ["VFF", "NASDAQ", "cannabis", "cannabis"],
    ["CHWY", "NYSE", "communications", "internet"],
    ["AAPL", "NASDAQ", "technology", "computers"],
    ["RIO", "NYSE", "basicMaterials", "mining"],
    ["MCHI", "NASDAQ", "etf", "china"],
    ["DQ", "NYSE", "basicMaterials", "china"],
    ["BILI", "NASDAQ", "technology", "china"],
    ["KWEB", "ARCA", "etf", "china"],
    ["VNET", "NASDAQ", "communications", "china"],
    ["MAXR", "NYSE", "communications", "telecommunications"],
    ["FXI", "ARCA", "etf", "china"],
    ["MELI", "NASDAQ", "communications", "internet"],
    ["ICLN", "NASDAQ", "etf", "alternateEnergy"],
    ["ENPH", "NASDAQ", "energy", "alternateEnergy"],
    ["ARKK", "ARCA", "etf", "software"],
    ["BBY", "NYSE", "consumerCyclical", "retail"],
    ["APPS", "NASDAQ", "technology", "software"],
    ["LRCX", "NASDAQ", "technology", "semiconductors"],
    ["IBB", "NASDAQ", "etf", "biotechnology"],
    ["PENN", "NASDAQ", "consumerCyclical", "entertainment"],
    ["TAN", "ARCA", "etf", "alternateEnergy"],
    ["BHP", "NYSE", "uranium", "uranium"],
    ["MU", "NASDAQ", "technology", "semiconductors"],
    ["BIDU", "NASDAQ", "communications", "china"],
    ["CSIQ", "NASDAQ", "energy", "alternateEnergy"],
    ["DE", "NYSE", "industrial", "machinery"],
    ["GDS", "NASDAQ", "communications", "china"],
    ["VIPS", "NYSE", "communications", "china"],
    ["UUUU", "AMEX", "uranium", "uranium"],
    ["KLAC", "NASDAQ", "technology", "semiconductors"],
    ["JPM", "NYSE", "financial", "financial"],
    ["MLM", "NYSE", "industrial", "homeBuilders"],
    ["ESTC", "NYSE", "technology", "software"],
    ["ZS", "NASDAQ", "technology", "cybersecurity"],
    ["NXE", "AMEX", "uranium", "uranium"],
    ["FVRR", "NYSE", "communications", "internet"],
    ["RIOT", "NASDAQ", "blockchain", "blockchain"],
    ["IWM", "ARCA", "etf", "stock"],
    ["FSLR", "NASDAQ", "energy", "alternateEnergy"],
    ["XLF", "ARCA", "etf", "financial"],
    ["ETSY", "NASDAQ", "communications", "internet"],
    ["LOW", "NYSE", "consumerCyclical", "homeBuilders"],
    ["CRWD", "NASDAQ", "technology", "cybersecurity"],
    ["PTON", "NASDAQ", "consumerCyclical", "entertainment"],
    ["TSLA", "NASDAQ", "technology", "auto"],
    ["QCOM", "NASDAQ", "technology", "semiconductors"],
    ["QQQ", "NYSE", "etf", "technology"],
    ["CAT", "NYSE", "industrial", "machinery"],
    ["RUN", "NASDAQ", "energy", "alternateEnergy"],
    ["BLNK", "NASDAQ", "energy", "alternateEnergy"],
    ["SNAP", "NYSE", "communications", "internet"],
    ["TGT", "NYSE", "consumerCyclical", "retail"],
    ["TWLO", "NYSE", "technology", "software"],
    ["XHB", "ARCA", "etf", "homeBuilders"],
    ["Z", "NASDAQ", "communications", "internet"],
    ["JD", "NASDAQ", "communications", "china"],
    ["NIO", "NYSE", "consumerCyclical", "china"],
    ["PDD", "NASDAQ", "communications", "china"],
    ["IGV", "BATS", "etf", "software"],
    ["GOOGL", "NASDAQ", "communications", "fang"],
    ["NVAX", "NASDAQ", "consumerNonCyclical", "biotechnology"],
    ["OKTA", "NASDAQ", "technology", "software"],
    ["SE", "NYSE", "technology", "software"],
    ["CGC", "NASDAQ", "cannabis", "cannabis"],
    ["IIPR", "NYSE", "financial", "financial"],
    ["FTCH", "NYSE", "communications", "internet"],
    ["ZI", "NASDAQ", "technology", "software"],
    ["LAZR", "NASDAQ", "technology", "auto"],
    ["NEM", "NYSE", "goldmining", "goldmining"],
    ["MDB", "NASDAQ", "technology", "software"],
    ["FTNT", "NASDAQ", "technology", "cybersecurity"],
    ["BZH", "NYSE", "consumerCyclical", "homeBuilders"],
    ["XLK", "ARCA", "etf", "technology"],
]

# basket of securities with strong 200SMA support
SMA200_securities = [
    ["GLD", "ARCA", "preciousMetals", "gold"],
    ["ADBE", "NASDAQ", "technology", "software"],
    ["COST", "ARCA", "consumerCyclical", "retail"],
    ["FSLY", "NYSE", "technology", "software"],
    ["MSFT", "NASDAQ", "technology", "software"],
    ["NFLX", "NASDAQ", "communications", "fang"],
    ["NVDA", "NASDAQ", "technology", "semiconductors"],
    ["CCJ", "NYSE", "uranium", "uranium"],
    ["PINS", "NYSE", "communications", "internet"],
    ["HD", "NYSE", "consumerCyclical", "homeBuilders"],
    ["INTU", "NASDAQ", "technology", "software"],
    ["DECK", "NYSE", "consumerCyclical", "retail"],
    ["PG", "NYSE", "consumerNonCyclical", "retail"],
    ["ANTM", "NYSE", "consumerNonCyclical", "healthcare"],
    ["BABA", "NYSE", "communications", "china"],
    ["SQ", "NYSE", "technology", "software"],
    ["SBUX", "NASDAQ", "consumerCyclical", "retail"],
    ["XLE", "ARCA", "etf", "energy"],
    ["SHOP", "NYSE", "communications", "internet"],
    ["JO", "ARCA", "commodities", "coffee"],
    ["DDOG", "NASDAQ", "technology", "software"],
    ["NXPI", "NASDAQ", "technology", "semiconductors"],
    ["CHDN", "NASDAQ", "consumerCyclical", "entertainment"],
    ["TTD", "NASDAQ", "technology", "software"],
    ["TWTR", "NYSE", "communications", "internet"],
    ["UPS", "NYSE", "industrial", "transportation"],
    ["WMT", "NYSE", "consumerCyclical", "retail"],
    ["NET", "NYSE", "technology", "software"],
    ["DOCU", "NASDAQ", "technology", "software"],
    ["GPS", "NYSE", "consumerCyclical", "retail"],
    ["EDU", "NYSE", "consumerNonCyclical", "china"],
    ["SPY", "ARCA", "etf", "stock"],
    ["ATVI", "NASDAQ", "technology", "software"],
    ["UNP", "NYSE", "industrial", "transportation"],
    ["TEAM", "NASDAQ", "technology", "software"],
    ["IWB", "ARCA", "etf", "stock"],
    ["DOYU", "NASDAQ", "technology", "china"],
    ["PYPL", "NASDAQ", "technology", "software"],
    ["SEDG", "NASDAQ", "energy", "alternateEnergy"],
    ["DIA", "ARCA", "etf", "stock"],
    ["JKS", "NYSE", "energy", "china"],
    ["HTHT", "NASDAQ", "consumerCyclical", "china"],
    ["NFLX", "NASDAQ", "communications", "fang"],
    ["FB", "NASDAQ", "communications", "fang"],
    ["CRM", "NYSE", "technology", "software"],
    ["AMZN", "NASDAQ", "communications", "fang"],
    ["ZM", "NASDAQ", "technology", "software"],
    ["MRNA", "NASDAQ", "consumerNonCyclical", "biotechnology"],
    ["AMD", "NASDAQ", "technology", "semiconductors"],
]

# all securities, bollinger bands currently set to 2.5 standard deviations
lowerBB_securities = [
    ["APHA", "NASDAQ", "cannabis", "cannabis"],#300; Exclude 200SMA
    ["XPER", "NASDAQ", "technology", "software"],#298; Exclude 200SMA
    ["ACB", "NYSE", "cannabis", "cannabis"],#292; Exclude 200SMA
    ["GRWG", "NASDAQ", "cannabis", "cannabis"],#290; Exclude 200SMA
    ["USO", "ARCA", "etf", "energy"],#289; Exclude 200SMA
    ["OIH", "ARCA", "etf", "energy"],#285; Exclude 200SMA
    ["SMH", "NASDAQ", "etf", "semiconductors"],#283; Exclude 200SMA
    ["SRAC", "NASDAQ", "cannabis", "cannabis"],#271; Exclude 200SMA
    ["ONEM", "NASDAQ", "technology", "software"],#249; Exclude 200SMA
    ["DADA", "NASDAQ", "communications", "internet"],#161; Exclude 50SMA 200SMA
    ["MGNI", "NASDAQ", "communications", "internet"],#159; Exclude 50SMA 200SMA
    ["LMND", "NYSE", "financial", "financial"],#143; Exclude 50SMA 200SMA
    ["LI", "NASDAQ", "consumerCyclical", "auto"],#124; 40 days, only include 9SMA and 20SMA
    ["XPEV", "NYSE", "consumerCyclical", "auto"],#104; 40 days, only include 9SMA and 20SMA
    ["MSOS", "ARCA", "etf", "cannabis"],#100; 40 days, only include 9SMA and 20SMA
    ["CRSR", "NASDAQ", "technology", "computers"],#86; 40 days, only include 9SMA and 20SMA
    ["CTEC", "NASDAQ", "etf", "alternateEnergy"],#60; 40 days, only include 9SMA and 20SMA
    ["ESTC", "NYSE", "technology", "software"],
    ["FNV", "NYSE", "goldmining", "goldmining"],
    ["GDX", "ARCA", "goldmining", "goldmining"],
    ["gold", "NYSE", "goldmining", "goldmining"],
    ["IWM", "ARCA", "etf", "stock"],
    ["TLT", "NASDAQ", "etf", "treasuries"],
    ["BABA", "NYSE", "communications", "china"],
    ["BGNE", "NASDAQ", "consumerNonCyclical", "china"],
    ["BILI", "NASDAQ", "technology", "china"],
    ["DQ", "NYSE", "basicMaterials", "china"],
    ["FUTU", "NASDAQ", "financial", "china"],
    ["FXI", "ARCA", "etf", "china"],
    ["GDS", "NASDAQ", "communications", "china"],
    ["IQ", "NASDAQ", "communications", "china"],
    ["JMIA", "NYSE", "communications", "china"],
    ["KWEB", "ARCA", "etf", "china"],
    ["MCHI", "NASDAQ", "etf", "china"],
    ["NIU", "NASDAQ", "consumerCyclical", "china"],
    ["NTES", "NASDAQ", "technology", "china"],
    ["SOL", "NYSE", "energy", "china"],
    ["TAL", "NYSE", "consumerNonCyclical", "china"],
    ["ZLAB", "NASDAQ", "consumerNonCyclical", "china"],
    ["ZTO", "NYSE", "industrial", "china"],
    ["LRCX", "NASDAQ", "technology", "semiconductors"],
    ["KLAC", "NASDAQ", "technology", "semiconductors"],
    ["TDOC", "NYSE", "technology", "software"],
    ["BIDU", "NASDAQ", "communications", "china"],
    ["UUP", "ARCA", "etf", "treasuries"],
    ["SPCE", "NYSE", "technology", "auto"],
    ["IRDM", "NASDAQ", "communications", "telecommunications"],
    ["DDD", "NYSE", "technology", "computers"],
    ["IBB", "NASDAQ", "etf", "biotechnology"],
    ["ATVI", "NASDAQ", "technology", "software"],
    ["VFF", "NASDAQ", "cannabis", "cannabis"],
    ["CRON", "NASDAQ", "cannabis", "cannabis"],
    ["RIO", "NYSE", "basicMaterials", "mining"],
    ["BHP", "NYSE", "uranium", "uranium"],
    ["DIA", "ARCA", "etf", "stock"],
    ["EBAY", "NASDAQ", "communications", "internet"],
    ["MU", "NASDAQ", "technology", "semiconductors"],
    ["CHWY", "NYSE", "communications", "internet"],
    ["MARA", "NASDAQ", "blockchain", "blockchain"],
    ["EEM", "ARCA", "etf", "china"],
    ["FVRR", "NYSE", "communications", "internet"],
    ["VNET", "NASDAQ", "communications", "china"],
    ["FCEL", "NASDAQ", "energy", "alternateEnergy"],
    ["ROKU", "NASDAQ", "communications", "internet"],
    ["SPY", "ARCA", "etf", "stock"],
    ["XRT", "ARCA", "etf", "retail"],
    ["ZS", "NASDAQ", "technology", "cybersecurity"],
    ["VIPS", "NYSE", "communications", "china"],
    ["PLUG", "NASDAQ", "energy", "alternateEnergy"],
    ["MLM", "NYSE", "industrial", "homeBuilders"],
    ["TAN", "ARCA", "etf", "alternateEnergy"],
    ["PYPL", "NASDAQ", "technology", "software"],
    ["APPS", "NASDAQ", "technology", "software"],
    ["PENN", "NASDAQ", "consumerCyclical", "entertainment"],
    ["MELI", "NASDAQ", "communications", "internet"],
    ["ENPH", "NASDAQ", "energy", "alternateEnergy"],
    ["PBW", "ARCA", "etf", "alternateEnergy"],
    ["ICLN", "NASDAQ", "etf", "alternateEnergy"],
    ["SPWR", "NASDAQ", "energy", "alternateEnergy"],
    ["CYBR", "NASDAQ", "technology", "cybersecurity"],
    ["NXPI", "NASDAQ", "technology", "semiconductors"],
    ["ARKK", "ARCA", "etf", "software"],
    ["IWB", "ARCA", "etf", "stock"],
    ["YOLO", "ARCA", "etf", "cannabis"],
    ["THCX", "ARCA", "etf", "cannabis"],
    ["MJ", "ARCA", "etf", "cannabis"],
    ["TLRY", "NASDAQ", "cannabis", "cannabis"],
    ["MAXR", "NYSE", "communications", "telecommunications"],
    ["DE", "NYSE", "industrial", "machinery"],
    ["SLV", "ARCA", "preciousMetals", "silver"],
    ["AAPL", "NASDAQ", "technology", "computers"],
    ["BBY", "NYSE", "consumerCyclical", "retail"],
    ["CSIQ", "NASDAQ", "energy", "alternateEnergy"],
    ["DDOG", "NASDAQ", "technology", "software"],
    ["UUUU", "AMEX", "uranium", "uranium"],
    ["JPM", "NYSE", "financial", "financial"],
    ["CCJ", "NYSE", "uranium", "uranium"],
    ["NXE", "AMEX", "uranium", "uranium"],
    ["RIOT", "NASDAQ", "blockchain", "blockchain"],
    ["DECK", "NYSE", "consumerCyclical", "retail"],
    ["DOCU", "NASDAQ", "technology", "software"],
    ["JO", "ARCA", "commodities", "coffee"],
    ["FSLR", "NASDAQ", "energy", "alternateEnergy"],
    ["XLF", "ARCA", "etf", "financial"],
    ["ETSY", "NASDAQ", "communications", "internet"],
    ["GPS", "NYSE", "consumerCyclical", "retail"],
    ["HD", "NYSE", "consumerCyclical", "homeBuilders"],
    ["LOW", "NYSE", "consumerCyclical", "homeBuilders"],
    ["CRWD", "NASDAQ", "technology", "cybersecurity"],
    ["NET", "NYSE", "technology", "software"],
    ["PINS", "NYSE", "communications", "internet"],
    ["PTON", "NASDAQ", "consumerCyclical", "entertainment"],
    ["XLE", "ARCA", "etf", "energy"],
    ["TSLA", "NASDAQ", "technology", "auto"],
    ["QCOM", "NASDAQ", "technology", "semiconductors"],
    ["QQQ", "NYSE", "etf", "technology"],
    ["CAT", "NYSE", "industrial", "machinery"],
    ["RUN", "NASDAQ", "energy", "alternateEnergy"],
    ["BLNK", "NASDAQ", "energy", "alternateEnergy"],
    ["SBUX", "NASDAQ", "consumerCyclical", "retail"],
    ["SNAP", "NYSE", "communications", "internet"],
    ["SQ", "NYSE", "technology", "software"],
    ["TGT", "NYSE", "consumerCyclical", "retail"],
    ["TWLO", "NYSE", "technology", "software"],
    ["XHB", "ARCA", "etf", "homeBuilders"],
    ["Z", "NASDAQ", "communications", "internet"],
    ["JD", "NASDAQ", "communications", "china"],
    ["NIO", "NYSE", "consumerCyclical", "china"],
    ["PDD", "NASDAQ", "communications", "china"],
    ["IGV", "BATS", "etf", "software"],
    ["TEAM", "NASDAQ", "technology", "software"],
    ["SEDG", "NASDAQ", "energy", "alternateEnergy"],
    ["INTU", "NASDAQ", "technology", "software"],
    ["GOOGL", "NASDAQ", "communications", "fang"],
    ["NVAX", "NASDAQ", "consumerNonCyclical", "biotechnology"],
    ["OKTA", "NASDAQ", "technology", "software"],
    ["SE", "NYSE", "technology", "software"],
    ["CHDN", "NASDAQ", "consumerCyclical", "entertainment"],
    ["CGC", "NASDAQ", "cannabis", "cannabis"],
    ["IIPR", "NYSE", "financial", "financial"],
    ["FTCH", "NYSE", "communications", "internet"],
    ["ZI", "NASDAQ", "technology", "software"],
    ["SHOP", "NYSE", "communications", "internet"],
    ["LAZR", "NASDAQ", "technology", "auto"],
    ["NEM", "NYSE", "goldmining", "goldmining"],
    ["MDB", "NASDAQ", "technology", "software"],
    ["FTNT", "NASDAQ", "technology", "cybersecurity"],
    ["BZH", "NYSE", "consumerCyclical", "homeBuilders"],
    ["XLK", "ARCA", "etf", "technology"],
    ["GLD", "ARCA", "preciousMetals", "gold"],
    ["ADBE", "NASDAQ", "technology", "software"],
    ["COST", "ARCA", "consumerCyclical", "retail"],
    ["FSLY", "NYSE", "technology", "software"],
    ["MSFT", "NASDAQ", "technology", "software"],
    ["NFLX", "NASDAQ", "communications", "fang"],
    ["NVDA", "NASDAQ", "technology", "semiconductors"],
    ["PG", "NYSE", "consumerNonCyclical", "retail"],
    ["ANTM", "NYSE", "consumerNonCyclical", "healthcare"],
    ["TTD", "NASDAQ", "technology", "software"],
    ["TWTR", "NYSE", "communications", "internet"],
    ["UPS", "NYSE", "industrial", "transportation"],
    ["WMT", "NYSE", "consumerCyclical", "retail"],
    ["EDU", "NYSE", "consumerNonCyclical", "china"],
    ["UNP", "NYSE", "industrial", "transportation"],
    ["DOYU", "NASDAQ", "technology", "china"],
    ["JKS", "NYSE", "energy", "china"],
    ["HTHT", "NASDAQ", "consumerCyclical", "china"],
    ["FB", "NASDAQ", "communications", "fang"],
    ["CRM", "NYSE", "technology", "software"],
    ["AMZN", "NASDAQ", "communications", "fang"],
    ["ZM", "NASDAQ", "technology", "software"],
    ["MRNA", "NASDAQ", "consumerNonCyclical", "biotechnology"],
    ["AMD", "NASDAQ", "technology", "semiconductors"],
]

# all securities, bollinger bands currently set to 2.5 standard deviations
upperBB_securities = [
    ["APHA", "NASDAQ", "cannabis", "cannabis"],#300; Exclude 200SMA
    ["XPER", "NASDAQ", "technology", "software"],#298; Exclude 200SMA
    ["ACB", "NYSE", "cannabis", "cannabis"],#292; Exclude 200SMA
    ["GRWG", "NASDAQ", "cannabis", "cannabis"],#290; Exclude 200SMA
    ["USO", "ARCA", "etf", "energy"],#289; Exclude 200SMA
    ["OIH", "ARCA", "etf", "energy"],#285; Exclude 200SMA
    ["SMH", "NASDAQ", "etf", "semiconductors"],#283; Exclude 200SMA
    ["SRAC", "NASDAQ", "cannabis", "cannabis"],#271; Exclude 200SMA
    ["ONEM", "NASDAQ", "technology", "software"],#249; Exclude 200SMA
    ["DADA", "NASDAQ", "communications", "internet"],#161; Exclude 50SMA 200SMA
    ["MGNI", "NASDAQ", "communications", "internet"],#159; Exclude 50SMA 200SMA
    ["LMND", "NYSE", "financial", "financial"],#143; Exclude 50SMA 200SMA
    ["LI", "NASDAQ", "consumerCyclical", "auto"],#124; 40 days, only include 9SMA and 20SMA
    ["XPEV", "NYSE", "consumerCyclical", "auto"],#104; 40 days, only include 9SMA and 20SMA
    ["MSOS", "ARCA", "etf", "cannabis"],#100; 40 days, only include 9SMA and 20SMA
    ["CRSR", "NASDAQ", "technology", "computers"],#86; 40 days, only include 9SMA and 20SMA
    ["CTEC", "NASDAQ", "etf", "alternateEnergy"],#60; 40 days, only include 9SMA and 20SMA
    ["ESTC", "NYSE", "technology", "software"],
    ["FNV", "NYSE", "goldmining", "goldmining"],
    ["GDX", "ARCA", "goldmining", "goldmining"],
    ["gold", "NYSE", "goldmining", "goldmining"],
    ["IWM", "ARCA", "etf", "stock"],
    ["TLT", "NASDAQ", "etf", "treasuries"],
    ["BABA", "NYSE", "communications", "china"],
    ["BGNE", "NASDAQ", "consumerNonCyclical", "china"],
    ["BILI", "NASDAQ", "technology", "china"],
    ["DQ", "NYSE", "basicMaterials", "china"],
    ["FUTU", "NASDAQ", "financial", "china"],
    ["FXI", "ARCA", "etf", "china"],
    ["GDS", "NASDAQ", "communications", "china"],
    ["IQ", "NASDAQ", "communications", "china"],
    ["JMIA", "NYSE", "communications", "china"],
    ["KWEB", "ARCA", "etf", "china"],
    ["MCHI", "NASDAQ", "etf", "china"],
    ["NIU", "NASDAQ", "consumerCyclical", "china"],
    ["NTES", "NASDAQ", "technology", "china"],
    ["SOL", "NYSE", "energy", "china"],
    ["TAL", "NYSE", "consumerNonCyclical", "china"],
    ["ZLAB", "NASDAQ", "consumerNonCyclical", "china"],
    ["ZTO", "NYSE", "industrial", "china"],
    ["LRCX", "NASDAQ", "technology", "semiconductors"],
    ["KLAC", "NASDAQ", "technology", "semiconductors"],
    ["TDOC", "NYSE", "technology", "software"],
    ["BIDU", "NASDAQ", "communications", "china"],
    ["UUP", "ARCA", "etf", "treasuries"],
    ["SPCE", "NYSE", "technology", "auto"],
    ["IRDM", "NASDAQ", "communications", "telecommunications"],
    ["DDD", "NYSE", "technology", "computers"],
    ["IBB", "NASDAQ", "etf", "biotechnology"],
    ["ATVI", "NASDAQ", "technology", "software"],
    ["VFF", "NASDAQ", "cannabis", "cannabis"],
    ["CRON", "NASDAQ", "cannabis", "cannabis"],
    ["RIO", "NYSE", "basicMaterials", "mining"],
    ["BHP", "NYSE", "uranium", "uranium"],
    ["DIA", "ARCA", "etf", "stock"],
    ["EBAY", "NASDAQ", "communications", "internet"],
    ["MU", "NASDAQ", "technology", "semiconductors"],
    ["CHWY", "NYSE", "communications", "internet"],
    ["MARA", "NASDAQ", "blockchain", "blockchain"],
    ["EEM", "ARCA", "etf", "china"],
    ["FVRR", "NYSE", "communications", "internet"],
    ["VNET", "NASDAQ", "communications", "china"],
    ["FCEL", "NASDAQ", "energy", "alternateEnergy"],
    ["ROKU", "NASDAQ", "communications", "internet"],
    ["SPY", "ARCA", "etf", "stock"],
    ["XRT", "ARCA", "etf", "retail"],
    ["ZS", "NASDAQ", "technology", "cybersecurity"],
    ["VIPS", "NYSE", "communications", "china"],
    ["PLUG", "NASDAQ", "energy", "alternateEnergy"],
    ["MLM", "NYSE", "industrial", "homeBuilders"],
    ["TAN", "ARCA", "etf", "alternateEnergy"],
    ["PYPL", "NASDAQ", "technology", "software"],
    ["APPS", "NASDAQ", "technology", "software"],
    ["PENN", "NASDAQ", "consumerCyclical", "entertainment"],
    ["MELI", "NASDAQ", "communications", "internet"],
    ["ENPH", "NASDAQ", "energy", "alternateEnergy"],
    ["PBW", "ARCA", "etf", "alternateEnergy"],
    ["ICLN", "NASDAQ", "etf", "alternateEnergy"],
    ["SPWR", "NASDAQ", "energy", "alternateEnergy"],
    ["CYBR", "NASDAQ", "technology", "cybersecurity"],
    ["NXPI", "NASDAQ", "technology", "semiconductors"],
    ["ARKK", "ARCA", "etf", "software"],
    ["IWB", "ARCA", "etf", "stock"],
    ["YOLO", "ARCA", "etf", "cannabis"],
    ["THCX", "ARCA", "etf", "cannabis"],
    ["MJ", "ARCA", "etf", "cannabis"],
    ["TLRY", "NASDAQ", "cannabis", "cannabis"],
    ["MAXR", "NYSE", "communications", "telecommunications"],
    ["DE", "NYSE", "industrial", "machinery"],
    ["SLV", "ARCA", "preciousMetals", "silver"],
    ["AAPL", "NASDAQ", "technology", "computers"],
    ["BBY", "NYSE", "consumerCyclical", "retail"],
    ["CSIQ", "NASDAQ", "energy", "alternateEnergy"],
    ["DDOG", "NASDAQ", "technology", "software"],
    ["UUUU", "AMEX", "uranium", "uranium"],
    ["JPM", "NYSE", "financial", "financial"],
    ["CCJ", "NYSE", "uranium", "uranium"],
    ["NXE", "AMEX", "uranium", "uranium"],
    ["RIOT", "NASDAQ", "blockchain", "blockchain"],
    ["DECK", "NYSE", "consumerCyclical", "retail"],
    ["DOCU", "NASDAQ", "technology", "software"],
    ["JO", "ARCA", "commodities", "coffee"],
    ["FSLR", "NASDAQ", "energy", "alternateEnergy"],
    ["XLF", "ARCA", "etf", "financial"],
    ["ETSY", "NASDAQ", "communications", "internet"],
    ["GPS", "NYSE", "consumerCyclical", "retail"],
    ["HD", "NYSE", "consumerCyclical", "homeBuilders"],
    ["LOW", "NYSE", "consumerCyclical", "homeBuilders"],
    ["CRWD", "NASDAQ", "technology", "cybersecurity"],
    ["NET", "NYSE", "technology", "software"],
    ["PINS", "NYSE", "communications", "internet"],
    ["PTON", "NASDAQ", "consumerCyclical", "entertainment"],
    ["XLE", "ARCA", "etf", "energy"],
    ["TSLA", "NASDAQ", "technology", "auto"],
    ["QCOM", "NASDAQ", "technology", "semiconductors"],
    ["QQQ", "NYSE", "etf", "technology"],
    ["CAT", "NYSE", "industrial", "machinery"],
    ["RUN", "NASDAQ", "energy", "alternateEnergy"],
    ["BLNK", "NASDAQ", "energy", "alternateEnergy"],
    ["SBUX", "NASDAQ", "consumerCyclical", "retail"],
    ["SNAP", "NYSE", "communications", "internet"],
    ["SQ", "NYSE", "technology", "software"],
    ["TGT", "NYSE", "consumerCyclical", "retail"],
    ["TWLO", "NYSE", "technology", "software"],
    ["XHB", "ARCA", "etf", "homeBuilders"],
    ["Z", "NASDAQ", "communications", "internet"],
    ["JD", "NASDAQ", "communications", "china"],
    ["NIO", "NYSE", "consumerCyclical", "china"],
    ["PDD", "NASDAQ", "communications", "china"],
    ["IGV", "BATS", "etf", "software"],
    ["TEAM", "NASDAQ", "technology", "software"],
    ["SEDG", "NASDAQ", "energy", "alternateEnergy"],
    ["INTU", "NASDAQ", "technology", "software"],
    ["GOOGL", "NASDAQ", "communications", "fang"],
    ["NVAX", "NASDAQ", "consumerNonCyclical", "biotechnology"],
    ["OKTA", "NASDAQ", "technology", "software"],
    ["SE", "NYSE", "technology", "software"],
    ["CHDN", "NASDAQ", "consumerCyclical", "entertainment"],
    ["CGC", "NASDAQ", "cannabis", "cannabis"],
    ["IIPR", "NYSE", "financial", "financial"],
    ["FTCH", "NYSE", "communications", "internet"],
    ["ZI", "NASDAQ", "technology", "software"],
    ["SHOP", "NYSE", "communications", "internet"],
    ["LAZR", "NASDAQ", "technology", "auto"],
    ["NEM", "NYSE", "goldmining", "goldmining"],
    ["MDB", "NASDAQ", "technology", "software"],
    ["FTNT", "NASDAQ", "technology", "cybersecurity"],
    ["BZH", "NYSE", "consumerCyclical", "homeBuilders"],
    ["XLK", "ARCA", "etf", "technology"],
    ["GLD", "ARCA", "preciousMetals", "gold"],
    ["ADBE", "NASDAQ", "technology", "software"],
    ["COST", "ARCA", "consumerCyclical", "retail"],
    ["FSLY", "NYSE", "technology", "software"],
    ["MSFT", "NASDAQ", "technology", "software"],
    ["NVDA", "NASDAQ", "technology", "semiconductors"],
    ["PG", "NYSE", "consumerNonCyclical", "retail"],
    ["ANTM", "NYSE", "consumerNonCyclical", "healthcare"],
    ["TTD", "NASDAQ", "technology", "software"],
    ["TWTR", "NYSE", "communications", "internet"],
    ["UPS", "NYSE", "industrial", "transportation"],
    ["WMT", "NYSE", "consumerCyclical", "retail"],
    ["EDU", "NYSE", "consumerNonCyclical", "china"],
    ["UNP", "NYSE", "industrial", "transportation"],
    ["DOYU", "NASDAQ", "technology", "china"],
    ["JKS", "NYSE", "energy", "china"],
    ["HTHT", "NASDAQ", "consumerCyclical", "china"],
    ["NFLX", "NASDAQ", "communications", "fang"],
    ["FB", "NASDAQ", "communications", "fang"],
    ["CRM", "NYSE", "technology", "software"],
    ["AMZN", "NASDAQ", "communications", "fang"],
    ["ZM", "NASDAQ", "technology", "software"],
    ["MRNA", "NASDAQ", "consumerNonCyclical", "biotechnology"],
    ["AMD", "NASDAQ", "technology", "semiconductors"],
]

# def appendBuckets(bucketToAppend):
#     for nakedsecurity in range(len(bucketToAppend)):
#         for clothedsecurity in range(len(industry_category_subcategory)):
#             if bucketToAppend[nakedsecurity][0] == industry_category_subcategory[clothedsecurity][0]:
#                 bucketToAppend[nakedsecurity].append(industry_category_subcategory[clothedsecurity][2])
#                 bucketToAppend[nakedsecurity].append(industry_category_subcategory[clothedsecurity][3])
#     return bucketToAppend
# print(appendBuckets(SMA9_securities))
#
# def checkLength(bucketToCheck):
#     for list in range(len(bucketToCheck)):
#         if len(bucketToCheck[list]) != 4:
#             print(f'''Check {bucketToCheck[list]}''')
#     print('Checked bucket.')
# checkLength(SMA9_securities)


##industry and sector watchlist frequency dictionary
#
# # from operator import itemgetter
# # sorted(industry_category_subcategory, key=itemgetter(2))
#
# industries = []
# categories = []
# for stock in range(len(upperBB_securities)):
#     if upperBB_securities[stock][2] not in industries:
#         industries.append(upperBB_securities[stock][2])
#     if upperBB_securities[stock][3] not in categories:
#         categories.append(upperBB_securities[stock][3])
# # print(f'''
# #
# # Industries: {industries}
# #
# # Categories: {categories}''')
# 
# def industry_category_subcategory_Sector_Dict(listOfInterest, listnum):
#     dict = {}
#     total = len(industry_category_subcategory)
#     for item in range(len(listOfInterest)):
#         name = listOfInterest[item]
#         count = 0
#         for stock in range(len(industry_category_subcategory)):
#             if industry_category_subcategory[stock][listnum] == name:
#                 count +=1
#         # print(f'''{name}: {count}; {round((count/total)*100, 2)}%''')
#         dict[name] = [count, round((count/total)*100, 2)]
#     dict['total'] = [total, round((total/total)*100, 2)]
#     return dict
# 
# print(industry_category_subcategory_Sector_Dict(industries, 2))
# print(industry_category_subcategory_Sector_Dict(categories, 3))
