# basket of securities with strong 9SMA support
SMA9_securities = [
    # ['FNV', 'NYSE'],
    # ['GDX', 'ARCA'],
    # ['gold', 'NYSE'],
    ['TLT', 'NASDAQ'],
    ['FUTU', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['TAL', 'NYSE'],
    ['ZTO', 'NYSE'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
]

# basket of securities with strong 20SMA support
SMA20_securities = [
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    # ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    # ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    # ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['CRON', 'NASDAQ'],
    ['BGNE', 'NASDAQ'],
    ['EBAY', 'NASDAQ'],
    ['ZLAB', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['TDOC', 'NYSE'],
    ['XRT', 'ARCA'],
    ['PLUG', 'NASDAQ'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],

]

# basket of securities with strong 50SMA support
SMA50_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA  SHORT CANDIDATE
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    ['SLV', 'ARCA'],
    ['EEM', 'ARCA'],
    ['SOL', 'NYSE'],
    ['NTES', 'NASDAQ'],
    ['MARA', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['ROKU', 'NASDAQ'],
    ['NIU', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['AAPL', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['MCHI', 'NASDAQ'],
    ['DQ', 'NYSE'],
    ['BILI', 'NASDAQ'],
    ['KWEB', 'ARCA'],
    ['VNET', 'NASDAQ'],
    ['MAXR', 'NYSE'],
    ['FXI', 'ARCA'],
    ['MELI', 'NASDAQ'],
    ['ICLN', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['BBY', 'NYSE'],
    ['APPS', 'NASDAQ'],
    ['LRCX', 'NASDAQ'],
    ['IBB', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['TAN', 'ARCA'],
    ['BHP', 'NYSE'],
    ['MU', 'NASDAQ'],
    ['BIDU', 'NASDAQ'],
    ['CSIQ', 'NASDAQ'],
    ['DE', 'NYSE'],
    ['GDS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['UUUU', 'AMEX'],
    ['KLAC', 'NASDAQ'],
    ['JPM', 'NYSE'],
    ['MLM', 'NYSE'],
    ['ESTC', 'NYSE'],
    ['ZS', 'NASDAQ'],
    ['NXE', 'AMEX'],
    ['FVRR', 'NYSE'],
    ['RIOT', 'NASDAQ'],
    ['IWM', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['PTON', 'NASDAQ'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['LAZR', 'NASDAQ'],
    # ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA']
]

# basket of securities with strong 200SMA support
SMA200_securities = [
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['CCJ', 'NYSE'],
    ['PINS', 'NYSE'],
    ['HD', 'NYSE'],
    ['INTU', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['PG', 'NYSE'],    #SHORT CANDIDATE
    ['ANTM', 'NYSE'],
    ['BABA', 'NYSE'],
    ['SQ', 'NYSE'],
    ['SBUX', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['SHOP', 'NYSE'],
    ['JO', 'ARCA'],
    ['DDOG', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['CHDN', 'NASDAQ'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['NET', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['EDU', 'NYSE'],
    ['SPY', 'ARCA'],
    ['ATVI', 'NASDAQ'],
    ['UNP', 'NYSE'],
    ['TEAM', 'NASDAQ'],
    ['IWB', 'ARCA'],
    ['DOYU', 'NASDAQ'],
    ['PYPL', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['DIA', 'ARCA'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

# all securities, bollinger bands currently set to 2.5 standard deviations
lowerBB_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['ESTC', 'NYSE'],
    ['FNV', 'NYSE'],
    ['GDX', 'ARCA'],
    ['gold', 'NYSE'],
    ['IWM', 'ARCA'],
    ['TLT', 'NASDAQ'],
    ['BABA', 'NYSE'],
    ['BGNE', 'NASDAQ'],
    ['BILI', 'NASDAQ'],
    ['DQ', 'NYSE'],
    ['FUTU', 'NASDAQ'],
    ['FXI', 'ARCA'],
    ['GDS', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['KWEB', 'ARCA'],
    ['MCHI', 'NASDAQ'],
    ['NIU', 'NASDAQ'],
    ['NTES', 'NASDAQ'],
    ['SOL', 'NYSE'],
    ['TAL', 'NYSE'],
    ['ZLAB', 'NASDAQ'],
    ['ZTO', 'NYSE'],
    ['LRCX', 'NASDAQ'],
    ['KLAC', 'NASDAQ'],
    ['TDOC', 'NYSE'],
    ['BIDU', 'NASDAQ'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
    ['IBB', 'NASDAQ'],
    ['ATVI', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['CRON', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['BHP', 'NYSE'],
    ['DIA', 'ARCA'],
    ['EBAY', 'NASDAQ'],
    ['MU', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['MARA', 'NASDAQ'],
    ['EEM', 'ARCA'],
    ['FVRR', 'NYSE'],
    ['VNET', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['ROKU', 'NASDAQ'],
    ['SPY', 'ARCA'],
    ['XRT', 'ARCA'],
    ['ZS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['PLUG', 'NASDAQ'],
    ['MLM', 'NYSE'],
    ['TAN', 'ARCA'],
    ['PYPL', 'NASDAQ'],
    ['APPS', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['MELI', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['ICLN', 'NASDAQ'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['IWB', 'ARCA'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],
    ['MAXR', 'NYSE'],
    ['DE', 'NYSE'],
    ['SLV', 'ARCA'],
    ['AAPL', 'NASDAQ'],
    ['BBY', 'NYSE'],
    ['CSIQ', 'NASDAQ'],
    ['DDOG', 'NASDAQ'],
    ['UUUU', 'AMEX'],
    ['JPM', 'NYSE'],
    ['CCJ', 'NYSE'],
    ['NXE', 'AMEX'],
    ['RIOT', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['JO', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['HD', 'NYSE'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['NET', 'NYSE'],
    ['PINS', 'NYSE'],
    ['PTON', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SBUX', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['SQ', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['TEAM', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['INTU', 'NASDAQ'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CHDN', 'NASDAQ'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['SHOP', 'NYSE'],
    ['LAZR', 'NASDAQ'],
    ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA'],
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['PG', 'NYSE'],
    ['ANTM', 'NYSE'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['EDU', 'NYSE'],
    ['UNP', 'NYSE'],
    ['DOYU', 'NASDAQ'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

# all securities, bollinger bands currently set to 2.5 standard deviations
upperBB_securities = [
    ['APHA', 'NASDAQ'],#300; Exclude 200SMA
    ['XPER', 'NASDAQ'],#298; Exclude 200SMA
    ['ACB', 'NYSE'],#292; Exclude 200SMA
    ['GRWG', 'NASDAQ'],#290; Exclude 200SMA
    ['USO', 'ARCA'],#289; Exclude 200SMA
    ['OIH', 'ARCA'],#285; Exclude 200SMA
    ['SMH', 'NASDAQ'],#283; Exclude 200SMA
    ['SRAC', 'NASDAQ'],#271; Exclude 200SMA
    ['ONEM', 'NASDAQ'],#249; Exclude 200SMA
    ['DADA', 'NASDAQ'],#161; Exclude 50SMA 200SMA
    ['MGNI', 'NASDAQ'],#159; Exclude 50SMA 200SMA
    ['LMND', 'NYSE'],#143; Exclude 50SMA 200SMA
    ['LI', 'NASDAQ'],#124; 40 days, only include 9SMA and 20SMA
    ['XPEV', 'NYSE'],#104; 40 days, only include 9SMA and 20SMA
    ['MSOS', 'ARCA'],#100; 40 days, only include 9SMA and 20SMA
    ['CRSR', 'NASDAQ'],#86; 40 days, only include 9SMA and 20SMA
    ['CTEC', 'NASDAQ'],#60; 40 days, only include 9SMA and 20SMA
    ['ESTC', 'NYSE'],
    ['FNV', 'NYSE'],
    ['GDX', 'ARCA'],
    ['gold', 'NYSE'],
    ['IWM', 'ARCA'],
    ['TLT', 'NASDAQ'],
    ['BABA', 'NYSE'],
    ['BGNE', 'NASDAQ'],
    ['BILI', 'NASDAQ'],
    ['DQ', 'NYSE'],
    ['FUTU', 'NASDAQ'],
    ['FXI', 'ARCA'],
    ['GDS', 'NASDAQ'],
    ['IQ', 'NASDAQ'],
    ['JMIA', 'NYSE'],
    ['KWEB', 'ARCA'],
    ['MCHI', 'NASDAQ'],
    ['NIU', 'NASDAQ'],
    ['NTES', 'NASDAQ'],
    ['SOL', 'NYSE'],
    ['TAL', 'NYSE'],
    ['ZLAB', 'NASDAQ'],
    ['ZTO', 'NYSE'],
    ['LRCX', 'NASDAQ'],
    ['KLAC', 'NASDAQ'],
    ['TDOC', 'NYSE'],
    ['BIDU', 'NASDAQ'],
    ['UUP', 'ARCA'],
    ['SPCE', 'NYSE'],
    ['IRDM', 'NASDAQ'],
    ['DDD', 'NYSE'],
    ['IBB', 'NASDAQ'],
    ['ATVI', 'NASDAQ'],
    ['VFF', 'NASDAQ'],
    ['CRON', 'NASDAQ'],
    ['RIO', 'NYSE'],
    ['BHP', 'NYSE'],
    ['DIA', 'ARCA'],
    ['EBAY', 'NASDAQ'],
    ['MU', 'NASDAQ'],
    ['CHWY', 'NYSE'],
    ['MARA', 'NASDAQ'],
    ['EEM', 'ARCA'],
    ['FVRR', 'NYSE'],
    ['VNET', 'NASDAQ'],
    ['FCEL', 'NASDAQ'],
    ['ROKU', 'NASDAQ'],
    ['SPY', 'ARCA'],
    ['XRT', 'ARCA'],
    ['ZS', 'NASDAQ'],
    ['VIPS', 'NYSE'],
    ['PLUG', 'NASDAQ'],
    ['MLM', 'NYSE'],
    ['TAN', 'ARCA'],
    ['PYPL', 'NASDAQ'],
    ['APPS', 'NASDAQ'],
    ['PENN', 'NASDAQ'],
    ['MELI', 'NASDAQ'],
    ['ENPH', 'NASDAQ'],
    ['PBW', 'ARCA'],
    ['ICLN', 'NASDAQ'],
    ['SPWR', 'NASDAQ'],
    ['CYBR', 'NASDAQ'],
    ['NXPI', 'NASDAQ'],
    ['ARKK', 'ARCA'],
    ['IWB', 'ARCA'],
    ['YOLO', 'ARCA'],
    ['THCX', 'ARCA'],
    ['MJ', 'ARCA'],
    ['TLRY', 'NASDAQ'],
    ['MAXR', 'NYSE'],
    ['DE', 'NYSE'],
    ['SLV', 'ARCA'],
    ['AAPL', 'NASDAQ'],
    ['BBY', 'NYSE'],
    ['CSIQ', 'NASDAQ'],
    ['DDOG', 'NASDAQ'],
    ['UUUU', 'AMEX'],
    ['JPM', 'NYSE'],
    ['CCJ', 'NYSE'],
    ['NXE', 'AMEX'],
    ['RIOT', 'NASDAQ'],
    ['DECK', 'NYSE'],
    ['DOCU', 'NASDAQ'],
    ['JO', 'ARCA'],
    ['FSLR', 'NASDAQ'],
    ['XLF', 'ARCA'],
    ['ETSY', 'NASDAQ'],
    ['GPS', 'NYSE'],
    ['HD', 'NYSE'],
    ['LOW', 'NYSE'],
    ['CRWD', 'NASDAQ'],
    ['NET', 'NYSE'],
    ['PINS', 'NYSE'],
    ['PTON', 'NASDAQ'],
    ['XLE', 'ARCA'],
    ['TSLA', 'NASDAQ'],
    ['QCOM', 'NASDAQ'],
    ['QQQ', 'NYSE'],
    ['CAT', 'NYSE'],
    ['RUN', 'NASDAQ'],
    ['BLNK', 'NASDAQ'],
    ['SBUX', 'NASDAQ'],
    ['SNAP', 'NYSE'],
    ['SQ', 'NYSE'],
    ['TGT', 'NYSE'],
    ['TWLO', 'NYSE'],
    ['XHB', 'ARCA'],
    ['Z', 'NASDAQ'],
    ['JD', 'NASDAQ'],
    ['NIO', 'NYSE'],
    ['PDD', 'NASDAQ'],
    ['IGV', 'BATS'],
    ['TEAM', 'NASDAQ'],
    ['SEDG', 'NASDAQ'],
    ['INTU', 'NASDAQ'],
    ['GOOGL', 'NASDAQ'],
    ['NVAX', 'NASDAQ'],
    ['OKTA', 'NASDAQ'],
    ['SE', 'NYSE'],
    ['CHDN', 'NASDAQ'],
    ['CGC', 'NASDAQ'],
    ['IIPR', 'NYSE'],
    ['FTCH', 'NYSE'],
    ['ZI', 'NASDAQ'],
    ['SHOP', 'NYSE'],
    ['LAZR', 'NASDAQ'],
    ['NEM', 'NYSE'],
    ['MDB', 'NASDAQ'],
    ['FTNT', 'NASDAQ'],
    ['BZH', 'NYSE'],
    ['XLK', 'ARCA'],
    ['GLD', 'ARCA'],
    ['ADBE', 'NASDAQ'],
    ['COST', 'ARCA'],
    ['FSLY', 'NYSE'],
    ['MSFT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['NVDA', 'NASDAQ'],
    ['PG', 'NYSE'],
    ['ANTM', 'NYSE'],
    ['TTD', 'NASDAQ'],
    ['TWTR', 'NYSE'],
    ['UPS', 'NYSE'],
    ['WMT', 'NYSE'],
    ['EDU', 'NYSE'],
    ['UNP', 'NYSE'],
    ['DOYU', 'NASDAQ'],
    ['JKS', 'NYSE'],
    ['HTHT', 'NASDAQ'],
    ['NFLX', 'NASDAQ'],
    ['FB', 'NASDAQ'],
    ['CRM', 'NYSE'],
    ['AMZN', 'NASDAQ'],
    ['ZM', 'NASDAQ'],
    ['MRNA', 'NASDAQ'],
    ['AMD', 'NASDAQ']
]

# may be using this list to further refactor code sometime in the future
buckets = [
    [SMA9_securities, 'sma9'],
    [SMA20_securities, 'sma20'],
    [SMA50_securities, 'sma50'],
    [SMA200_securities, 'sma200'],
    [lowerBB_securities, 'lowerbb'],
    [upperBB_securities, 'upperbb']
]

# full list of securities with Industry, Category, Subcategory
industry_category_subcategory = [
    ["USO", "ARCA", "etf", "energy"],
    ["OIH", "ARCA", "etf", "energy"],
    ["SMH", "NASDAQ", "etf", "semiconductors"],
    ["MSOS", "ARCA", "etf", "cannabis"],
    ["CTEC", "NASDAQ", "etf", "alternateEnergy"],
    ["GDX", "ARCA", "goldmining", "goldmining"],
    ["IWM", "ARCA", "etf", "stock"],
    ["TLT", "NASDAQ", "etf", "treasuries"],
    ["FXI", "ARCA", "etf", "china"],
    ["KWEB", "ARCA", "etf", "china"],
    ["MCHI", "NASDAQ", "etf", "china"],
    ["UUP", "ARCA", "etf", "usd"],
    ["IBB", "NASDAQ", "etf", "biotechnology"],
    ["DIA", "ARCA", "etf", "stock"],
    ["EEM", "ARCA", "etf", "china"],
    ["SPY", "ARCA", "etf", "stock"],
    ["XRT", "ARCA", "etf", "retail"],
    ["TAN", "ARCA", "etf", "alternateEnergy"],
    ["PBW", "ARCA", "etf", "alternateEnergy"],
    ["ICLN", "NASDAQ", "etf", "alternateEnergy"],
    ["ARKK", "ARCA", "etf", "software"],
    ["IWB", "ARCA", "etf", "stock"],
    ["YOLO", "ARCA", "etf", "cannabis"],
    ["THCX", "ARCA", "etf", "cannabis"],
    ["MJ", "ARCA", "etf", "cannabis"],
    ["SLV", "ARCA", "preciousMetals", "silver"],
    ["JO", "ARCA", "commodities", "coffee"],
    ["XLF", "ARCA", "etf", "financial"],
    ["XLE", "ARCA", "etf", "energy"],
    ["QQQ", "NYSE", "etf", "technology"],
    ["XHB", "ARCA", "etf", "homeBuilders"],
    ["IGV", "BATS", "etf", "software"],
    ["XLK", "ARCA", "etf", "technology"],
    ["GLD", "ARCA", "preciousMetals", "gold"],
    ["FNV", "NYSE", "goldmining", "goldmining"],
    ["gold", "NYSE", "goldmining", "goldmining"],
    ["DQ", "NYSE", "basicMaterials", "china"],
    ["RIO", "NYSE", "basicMaterials", "mining"],
    ["BHP", "NYSE", "uranium", "uranium"],
    ["UUUU", "AMEX", "uranium", "uranium"],
    ["CCJ", "NYSE", "uranium", "uranium"],
    ["NXE", "AMEX", "uranium", "uranium"],
    ["NEM", "NYSE", "goldmining", "goldmining"],
    ["DADA", "NASDAQ", "communications", "internet"],
    ["MGNI", "NASDAQ", "communications", "internet"],
    ["BABA", "NYSE", "communications", "china"],
    ["GDS", "NASDAQ", "communications", "china"],
    ["IQ", "NASDAQ", "communications", "china"],
    ["JMIA", "NYSE", "communications", "china"],
    ["BIDU", "NASDAQ", "communications", "china"],
    ["IRDM", "NASDAQ", "communications", "telecommunications"],
    ["EBAY", "NASDAQ", "communications", "internet"],
    ["CHWY", "NYSE", "communications", "internet"],
    ["FVRR", "NYSE", "communications", "internet"],
    ["VNET", "NASDAQ", "communications", "china"],
    ["ROKU", "NASDAQ", "communications", "internet"],
    ["VIPS", "NYSE", "communications", "china"],
    ["MELI", "NASDAQ", "communications", "internet"],
    ["MAXR", "NYSE", "communications", "telecommunications"],
    ["ETSY", "NASDAQ", "communications", "internet"],
    ["PINS", "NYSE", "communications", "internet"],
    ["SNAP", "NYSE", "communications", "internet"],
    ["Z", "NASDAQ", "communications", "internet"],
    ["JD", "NASDAQ", "communications", "china"],
    ["PDD", "NASDAQ", "communications", "china"],
    ["GOOGL", "NASDAQ", "communications", "fang"],
    ["OKTA", "NASDAQ", "technology", "software"],
    ["FTCH", "NYSE", "communications", "internet"],
    ["SHOP", "NYSE", "communications", "internet"],
    ["NFLX", "NASDAQ", "communications", "fang"],
    ["TTD", "NASDAQ", "technology", "software"],
    ["TWTR", "NYSE", "communications", "internet"],
    ["NFLX", "NASDAQ", "communications", "fang"],
    ["FB", "NASDAQ", "communications", "fang"],
    ["AMZN", "NASDAQ", "communications", "fang"],
    ["GRWG", "NASDAQ", "cannabis", "cannabis"],
    ["LI", "NASDAQ", "consumerCyclical", "auto"],
    ["XPEV", "NYSE", "consumerCyclical", "auto"],
    ["NIU", "NASDAQ", "consumerCyclical", "china"],
    ["SPCE", "NYSE", "technology", "auto"],
    ["PENN", "NASDAQ", "consumerCyclical", "entertainment"],
    ["BBY", "NYSE", "consumerCyclical", "retail"],
    ["DECK", "NYSE", "consumerCyclical", "retail"],
    ["GPS", "NYSE", "consumerCyclical", "retail"],
    ["HD", "NYSE", "consumerCyclical", "homeBuilders"],
    ["LOW", "NYSE", "consumerCyclical", "homeBuilders"],
    ["PTON", "NASDAQ", "consumerCyclical", "leisureTime"],
    ["TSLA", "NASDAQ", "technology", "auto"],
    ["SBUX", "NASDAQ", "consumerCyclical", "retail"],
    ["TGT", "NYSE", "consumerCyclical", "retail"],
    ["NIO", "NYSE", "consumerCyclical", "china"],
    ["CHDN", "NASDAQ", "consumerCyclical", "entertainment"],
    ["LAZR", "NASDAQ", "technology", "auto"],
    ["BZH", "NYSE", "consumerCyclical", "homeBuilders"],
    ["COST", "ARCA", "consumerCyclical", "retail"],
    ["WMT", "NYSE", "consumerCyclical", "retail"],
    ["HTHT", "NASDAQ", "consumerCyclical", "china"],
    ["APHA", "NASDAQ", "cannabis", "cannabis"],
    ["ACB", "NYSE", "cannabis", "cannabis"],
    ["BGNE", "NASDAQ", "consumerNonCyclical", "china"],
    ["TAL", "NYSE", "consumerNonCyclical", "china"],
    ["ZLAB", "NASDAQ", "consumerNonCyclical", "china"],
    ["TDOC", "NYSE", "technology", "software"],
    ["VFF", "NASDAQ", "cannabis", "cannabis"],
    ["CRON", "NASDAQ", "cannabis", "cannabis"],
    ["PYPL", "NASDAQ", "technology", "software"],
    ["TLRY", "NASDAQ", "cannabis", "cannabis"],
    ["RIOT", "NASDAQ", "blockchain", "blockchain"],
    ["SQ", "NYSE", "technology", "software"],
    ["NVAX", "NASDAQ", "consumerNonCyclical", "biotechnology"],
    ["CGC", "NASDAQ", "cannabis", "cannabis"],
    ["PG", "NYSE", "consumerNonCyclical", "consumerProducts"],
    ["ANTM", "NYSE", "consumerNonCyclical", "healthcare"],
    ["EDU", "NYSE", "consumerNonCyclical", "china"],
    ["MRNA", "NASDAQ", "consumerNonCyclical", "biotechnology"],
    ["SRAC", "NASDAQ", "cannabis", "cannabis"],
    ["MARA", "NASDAQ", "blockchain", "blockchain"],
    ["SOL", "NYSE", "energy", "china"],
    ["FCEL", "NASDAQ", "energy", "alternateEnergy"],
    ["PLUG", "NASDAQ", "energy", "alternateEnergy"],
    ["ENPH", "NASDAQ", "energy", "alternateEnergy"],
    ["SPWR", "NASDAQ", "energy", "alternateEnergy"],
    ["CSIQ", "NASDAQ", "energy", "alternateEnergy"],
    ["FSLR", "NASDAQ", "energy", "alternateEnergy"],
    ["RUN", "NASDAQ", "energy", "alternateEnergy"],
    ["SEDG", "NASDAQ", "energy", "alternateEnergy"],
    ["JKS", "NYSE", "energy", "china"],
    ["LMND", "NYSE", "financial", "insurance"],
    ["FUTU", "NASDAQ", "financial", "china"],
    ["JPM", "NYSE", "financial", "banks"],
    ["IIPR", "NYSE", "financial", "reits"],
    ["ZTO", "NYSE", "industrial", "china"],
    ["MLM", "NYSE", "industrial", "buildingMaterials"],
    ["DE", "NYSE", "industrial", "machinery"],
    ["CAT", "NYSE", "industrial", "machinery"],
    ["BLNK", "NASDAQ", "energy", "alternateEnergy"],
    ["UPS", "NYSE", "industrial", "transportation"],
    ["UNP", "NYSE", "industrial", "transportation"],
    ["XPER", "NASDAQ", "technology", "software"],
    ["ONEM", "NASDAQ", "technology", "software"],
    ["CRSR", "NASDAQ", "technology", "computers"],
    ["ESTC", "NYSE", "technology", "software"],
    ["BILI", "NASDAQ", "technology", "china"],
    ["NTES", "NASDAQ", "technology", "china"],
    ["LRCX", "NASDAQ", "technology", "semiconductors"],
    ["KLAC", "NASDAQ", "technology", "semiconductors"],
    ["DDD", "NYSE", "technology", "computers"],
    ["ATVI", "NASDAQ", "technology", "software"],
    ["MU", "NASDAQ", "technology", "semiconductors"],
    ["ZS", "NASDAQ", "technology", "cybersecurity"],
    ["APPS", "NASDAQ", "technology", "software"],
    ["CYBR", "NASDAQ", "technology", "cybersecurity"],
    ["NXPI", "NASDAQ", "technology", "semiconductors"],
    ["AAPL", "NASDAQ", "technology", "computers"],
    ["DDOG", "NASDAQ", "technology", "software"],
    ["DOCU", "NASDAQ", "technology", "software"],
    ["CRWD", "NASDAQ", "technology", "cybersecurity"],
    ["NET", "NYSE", "technology", "software"],
    ["QCOM", "NASDAQ", "technology", "semiconductors"],
    ["TWLO", "NYSE", "technology", "software"],
    ["TEAM", "NASDAQ", "technology", "software"],
    ["INTU", "NASDAQ", "technology", "software"],
    ["SE", "NYSE", "technology", "software"],
    ["ZI", "NASDAQ", "technology", "software"],
    ["MDB", "NASDAQ", "technology", "software"],
    ["FTNT", "NASDAQ", "technology", "cybersecurity"],
    ["ADBE", "NASDAQ", "technology", "software"],
    ["FSLY", "NYSE", "technology", "software"],
    ["MSFT", "NASDAQ", "technology", "software"],
    ["NVDA", "NASDAQ", "technology", "semiconductors"],
    ["DOYU", "NASDAQ", "technology", "china"],
    ["CRM", "NYSE", "technology", "software"],
    ["ZM", "NASDAQ", "technology", "software"],
    ["AMD", "NASDAQ", "technology", "semiconductors"]
]
